---
title: "Andy vs Adam 2016-2017"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(curl)

# setup auth
h <- new_handle()
handle_setheaders(h, "Authorization" = "Basic YW5keWN6ZXJ3b25rYTpwb2xvbmlh")

# player data
playersRaw <- read.csv(curl("https://www.mysportsfeeds.com/api/feed/pull/nhl/2016-2017-regular/cumulative_player_stats.csv?playerstats=Pts", handle = h))
players <- subset(
  playersRaw[, c(3,4,18,19)], 
  (X.LastName == "McDavid" & X.FirstName == "Connor") | (X.LastName == "Gaudreau" & X.FirstName == "Johnny")
  )
players <- players[order(players$X.LastName, decreasing=TRUE),]

#team data
teamsRaw <- read.csv(curl("https://www.mysportsfeeds.com/api/feed/pull/nhl/2016-2017/conference_team_standings.csv", handle = h))
teams <- subset(
  teamsRaw[, c(5,6,8,13,25)], 
  X.Team.Name == "Oilers" | X.Team.Name == "Flames"
)
teams <- teams[order(teams$X.Team.Name, decreasing=TRUE),]

# create a new table with Andy & Adam rows
totalPoints <- teams[, 4] + teams[, 5] + players[, 4]
gamesMissed <- teams[, 3] - players[, 3]
betStats <- data.frame(
  Who = c("Andy","Adam"),
  Team  = teams[, 2],
  Team.Games = teams[, 3],
  Team.Points = teams[, 4],
  Team.Goals = teams[, 5],
  Player  = players[, 1],
  Player.Points = players[, 4],
  Games.Missed = gamesMissed,
  Total = totalPoints
  )
```


### Rules
1. McDavid v Gaudreau Total Points
2. Oilers v Flames Total Points
3. Oilers v Flames Total Goals

Add 'em up at the end of the year and $10/pt up to $100.

**Note**: If either player misses 10 games, we strike the first part of the bet. 

## Stats
```{r table, echo=FALSE}
renderTable(betStats)
```

## Player Points
```{r player, echo=FALSE}
renderPlot({
  ggplot(data=betStats, aes(x=Player, y=Player.Points, fill=Player)) +  geom_bar(stat="identity")
})
```

## Team Stats
```{r team, echo=FALSE}
renderPlot({
  ggplot(data=betStats, aes(x=Team, y=Team.Points, fill=Team)) +  geom_bar(stat="identity")
})

renderPlot({
  ggplot(data=betStats, aes(x=Team, y=Team.Goals, fill=Team)) +  geom_bar(stat="identity")
})
```
Stats provided by [MySportsFeeds](https://www.mysportsfeeds.com/)

