---
title: "Andy vs Adam NHL Bet"
author: "Andy Czerwonka"
date: "October 28, 2016"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hey Adam, I think you screwed me again with the goals

## This is a title


```{r eruptions, echo=FALSE}

setwd("~/work/oilers")

#player data
playersRaw <- read.csv("./data/playerstats.csv")
players <- subset(
  playersRaw[, c(3,4,18,19)], 
  (X.LastName == "McDavid" & X.FirstName == "Connor") | (X.LastName == "Gaudreau" & X.FirstName == "Johnny")
  )
players <- players[order(players$X.LastName, decreasing=TRUE),]

#team data
teamsRaw <- read.csv("./data/teamstats.csv")
teams <- subset(
  teamsRaw[, c(5,6,8,13,25)], 
  X.Team.Name == "Oilers" | X.Team.Name == "Flames"
)
teams <- teams[order(teams$X.Team.Name, decreasing=TRUE),]


# create a new table with Andy & Adam rows
totalPoints <- teams[, 4] + teams[, 5] + players[, 4]
gamesMissed <- teams[, 3] - players[, 3]
betStats <- data.frame(
  Who = c("Andy","Adam"),
  Team  = teams[, 2],
  Team.Games = teams[, 3],
  Team.Points = teams[, 4],
  Team.Goals = teams[, 5],
  Player  = players[, 1],
  Player.Points = players[, 4],
  Games.Missed = gamesMissed,
  Total = totalPoints
  )

library(ggplot2)

renderPlot({
  ggplot(data=betStats, aes(x=Team, y=Team.Points, fill=Team)) +  geom_bar(stat="identity")
})

renderPlot({
  ggplot(data=betStats, aes(x=Team, y=Team.Goals, fill=Team)) +  geom_bar(stat="identity")
})

renderPlot({
  ggplot(data=betStats, aes(x=Player, y=Player.Points, fill=Player)) +  geom_bar(stat="identity")
})

 renderTable(betStats)
```




